sudo: true

language: rust

rust:
  - stable

before_install:
  - wget https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz
  - sudo tar -C /usr/local -xzf go1.13.7.linux-amd64.tar.gz
  - export PATH=$PATH:/usr/local/go/bin
  - go version
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - make ci
