sudo: true

language: go

go:
  - master

before_install:
  - curl -sSf https://build.travis-ci.com/files/rustup-init.sh | sh -s -- --default-toolchain=stable --profile=minimal -y
  - source $HOME/.cargo/env
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - make ci
